# Generated by Django 4.1.13 on 2025-02-05 04:16

import app1.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField(unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('sensor_id', models.CharField(max_length=50, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sensor_data', djongo.models.fields.EmbeddedField(model_container=app1.models.SensorReading, null=True)),
                ('maintenance_history', djongo.models.fields.ArrayField(default=list, model_container=app1.models.MaintenanceLog)),
                ('analytics', djongo.models.fields.EmbeddedField(model_container=app1.models.Analytics, null=True)),
                ('metadata', djongo.models.fields.JSONField(default=dict)),
            ],
            options={
                'db_table': 'parking_slots',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
