# Generated by Django 4.1.13 on 2025-02-05 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_parkingslot_analytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='last_24h_occupancy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='last_24h_occupancy_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='occupation_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='total_occupancy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='total_occupancy_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
