# Generated by Django 4.1.13 on 2025-02-05 07:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_parkingslot_last_24h_occupancy_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], max_length=20)),
                ('duration', models.DurationField(default=datetime.timedelta)),
                ('occupancy_rate', models.FloatField(default=0)),
                ('occupied_count', models.IntegerField(default=0)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.parkingslot')),
            ],
            options={
                'db_table': 'parking_history',
            },
        ),
        migrations.AddIndex(
            model_name='parkinghistory',
            index=models.Index(fields=['timestamp'], name='parking_his_timesta_b82cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='parkinghistory',
            index=models.Index(fields=['slot', 'timestamp'], name='parking_his_slot_id_2fc5b8_idx'),
        ),
    ]
